### ISSUE TITLE
更新后查看画廊图片出现 Arg_DivideByZero 错误

### ISSUE THREAD

**Issue by TkzcM** [OpportunityLiu/E-Viewer#104]
![image](https://user-images.githubusercontent.com/45264418/54873748-598b6500-4e18-11e9-85d0-66b9299ae45c.png)
如图，所有画廊的图片都无法查看

**Comment by OpportunityLiu** [comment]
我这里没问题，日志发一下

**Comment by TkzcM** [comment]
```1[2019-03-24 02:35:29Z]
--------Exception Info--------
Type: System.DivideByZeroException
HResult: 0x80020012
HelpLink: 
Message: @"Arg_DivideByZero"
DisplayedMessage: @"Arg_DivideByZero"
Source: <unknown>
Data: empty
StackTrace:
     at ExViewer!<BaseAddress>+0x2013883
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5c60
     at SharedLibrary!<BaseAddress>+0x4d5be8
     at SharedLibrary!<BaseAddress>+0x4d5ba7
     at ExViewer!<BaseAddress>+0x2012d5d
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5c60
     at SharedLibrary!<BaseAddress>+0x4d5be8
     at SharedLibrary!<BaseAddress>+0x4d5ba7
     at ExViewer!<BaseAddress>+0x167e6a6
     at ExViewer!<BaseAddress>+0x1680b56
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5c60
     at SharedLibrary!<BaseAddress>+0x4d5be8
     at SharedLibrary!<BaseAddress>+0x4d5ba7
     at SharedLibrary!<BaseAddress>+0x54529b
     at ExViewer!<BaseAddress>+0x167e888
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5c60
     at SharedLibrary!<BaseAddress>+0x4d5be8
     at SharedLibrary!<BaseAddress>+0x4d5ba7
     at SharedLibrary!<BaseAddress>+0x54529b
     at ExViewer!<BaseAddress>+0x167f3ac
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Opportunity.MvvmUniverse.DispatcherHelper.<>c__DisplayClass2_0.<ThrowUnhandledError>b__0()
     at System.Func<System.Nullable<System.Single>>.Invoke()
     at ExViewer!<BaseAddress>+0x220328c
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x4d5c60
     at SharedLibrary!<BaseAddress>+0x4d5be8
     at SharedLibrary!<BaseAddress>+0x4d5ba7
     at SharedLibrary!<BaseAddress>+0x54529b
     at ExViewer!<BaseAddress>+0x1874fe4
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at SharedLibrary!<BaseAddress>+0x65496e
     at SharedLibrary!<BaseAddress>+0x4f50d8
     at SharedLibrary!<BaseAddress>+0x4f543c
     at SharedLibrary!<BaseAddress>+0x4a0ad0
     at ExViewer!<BaseAddress>+0x1935db8
     at ExViewer!<BaseAddress>+0x1935cf4
     at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs eventArgs)
     at System.EventHandler<System.Threading.Tasks.UnobservedTaskExceptionEventArgs>.Invoke(Object sender, Threading.Tasks.UnobservedTaskExceptionEventArgs e)
     at ExViewer!<BaseAddress>+0x1aad6b6
     at ExViewer!<BaseAddress>+0x1aaddaf
Inner Exception: null
--------Other Info--------
Package: 2289Opportunity.E-Viewer_2019.3.23.0_x64__x517s75edqf2e @ f5129a33a0d487ab5488878cc4047a1203de1b55
FrameStack:
  ExViewer.Views.SearchPage, 
  ExViewer.Views.GalleryPage, 1386322
  >> ExViewer.Views.ImagePage <<
FlipView: SelectedIndex=0
Gallery: Type=ExClient.Galleries.Gallery, ID=1386322, Token=e1c051c19d

**Comment by OpportunityLiu** [comment]
e站的设置页面就从来没有对过。。。
真不知道那个html是怎么拼出来的
